### ISSUE TITLE
WORKS - thanks - some more info inside

### ISSUE THREAD

**Issue by smithsun00** [if-ai/ComfyUI-IF_MemoAvatar#14]
Might not be the correct place to right it - but I am putting this here for other also to see.

First of all thanks if-ai for the wrapper and your hard work.

I did not fully followed your instruction, as I saw I already have a ComfyUI installed with embedded_python that already had much of the requirements installed with the correct versions of packages.
So I decided to try it out.

My ComfyUI installation include python 3.11, using torch 2.5.1 with cuda 12.4 support.
Also xformers with cuda support.
I am using RTX 4090.

I had many issues during the installation process, but I started like this:
- Duplicated my ComfyUI repo to not ruin my current one while I test it.
- git cloned your repo into custom nodes.
- installed requirements.txt -> opened ComfyUI -> loaded the attached workflow.
- several issues I saw at this point - both your: ComfyUI-IF_AI_tools and ComfyUI-IF_MemoAvatar failed to load.
- At this point I removed the Show Text node from your ComfyUI-IF_AI_tools and replaced it with a normal Show Text node from ComfyUI.
- I checked the logs in the cmd window (windows) - copied it into a text editor and looked up the name MemoAvatar and saw I was missing some packages, like: triton, xformers (at this point I did not have it installed yet), then something another package each time - there were a couple of them - I used ChatGPT to see how to install them + make sure you do this with the supported cuda version if your torch is supporting it.
- after that I managed to remove all issues with loading the nodes from the workflow.

Trying to queue the workflow:
- I first come across some error about not being able to download the models - the connection to hugginface or loading the model failed - this was due to the code trying to load models and config from the vae folder which I was missing the sd-vae-ft-mse.bin file and the config file from that folder - if-ai said he updated the repo to not require it - to solve it either update the repo and see if it works for you, or just download the sd-vae-ft-mse.bin and config  - by looking it up in google - it is under a stabilityai repo - place it in your models/vae folder - keep the name as 'diffusion_pytorch_model.bin'.
- doing that I managed to move to the next stage - where I came across another error - about downloading the emotion2ven model - it seemed to scream a couple of things there about missing or incorrect tokenizer_conf.
I thought there was a problem downloading the model files - but checking the path:
F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\models\emotion2vec\emotion2vec_plus_large
some files including the model were there. The issue was that many files weren't and the files that were were not correct.
I found the repo in 
https://modelscope.cn/models/iic/emotion2vec_plus_large/files
and just cloned it into that path - this fixed my issue.
- Next I just clicked on Queue and it finally run correctly.

Thanks a bunch again man.

**Comment by if-ai** [comment]
I fixed it this thanks for pointing out the file.
