### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by tiandaoyuxi** [if-ai/ComfyUI-IF_MemoAvatar#15]
got prompt
Loading models
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'attention_type': 'default', 'center_input_sample': False, 'class_embeddings_concat': False, 'conv_in_kernel': 3, 'dropout': 0.0, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'mid_block_only_cross_attention': None, 'num_attention_heads': None, 'projection_class_embeddings_input_dim': None, 'reverse_transformer_layers_per_block': None, 'time_cond_proj_dim': None, 'time_embedding_act_fn': None, 'time_embedding_dim': None, 'time_embedding_type': 'positional', 'timestep_post_act': None, 'transformer_layers_per_block': 1} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
['zunlong.safetensors']
Models loaded successfully to cuda with dtype torch.float16
face_models path: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Comfy_UI\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
['zunlong.safetensors']
Separator version 0.21.2 instantiating with output_dir: D:\Comfy_UI\ComfyUI\temp\memo_audio_cache, output_format: WAV
Operating System: Windows 10.0.22631
System: Windows Node: TAOW-WS Release: 10 Machine: AMD64 Proc: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
Python Version: 3.11.9
PyTorch Version: 2.5.1+cu124
['zunlong.safetensors']
FFmpeg installed: ffmpeg version 2024-07-18-git-fa5a605542-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
ONNX Runtime GPU package installed with version: 1.20.1
ONNX Runtime CPU package installed with version: 1.20.1
CUDA is available in Torch, setting Torch device to CUDA
CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled
Loading model Kim_Vocal_2.onnx...
Load model duration: 00:00:00
Starting separation process for audio_file_path: D:\Comfy_UI\ComfyUI\temp\memo_audio_cache\resampled_1734488112.2220109-16k.wav
100%|████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.56s/it]
100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 16.03it/s]
Saving Vocals stem to resampled_1734488112.2220109-16k_(Vocals)_Kim_Vocal_2.wav...
Audio duration is 0.00 hours (4.21 seconds).
Using pydub for writing.
Clearing input audio file paths, sources and stems...
Separation duration: 00:00:03
Downloading emotion2vec models from modelscope
Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 139, in generate
    audio_emotion, num_emotion_classes = extract_audio_emotion_labels(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 174, in extract_audio_emotion_labels
    kwargs = download_model(model=emotion2vec_model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\funasr\download\download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\funasr\download\download_from_hub.py", line 67, in download_from_ms
    kwargs["tokenizer_conf"]["token_list"] = os.path.join(model_or_path, "tokens.txt")
    ~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key tokenizer_conf
    full_key: tokenizer_conf
    object_type=dict
Prompt executed in 11.48 seconds

**Comment by smithsun00** [comment]
Hi.
I had the same thing happening to me - you can have a look in my post "WORKS!!! thanks" for more details, but basically the files with the model downloaded from audio_utils.py or not correct.
Here is what I wrote:
I thought there was a problem downloading the model files - but checking the path:
F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\models\emotion2vec\emotion2vec_plus_large
some files including the model were there. The issue was that many files weren't and the files that were were not correct.
I found the repo in
https://modelscope.cn/models/iic/emotion2vec_plus_large/files

So just clone that repo into that path in your ComfyUI and the error should be gone.

**Comment by tiandaoyuxi** [comment]
> Hi. I had the same thing happening to me - you can have a look in my post "WORKS!!! thanks" for more details, but basically the files with the model downloaded from audio_utils.py or not correct. Here is what I wrote: I thought there was a problem downloading the model files - but checking the path: F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\models\emotion2vec\emotion2vec_plus_large some files including the model were there. The issue was that many files weren't and the files that were were not correct. I found the repo in https://modelscope.cn/models/iic/emotion2vec_plus_large/files
> 
> So just clone that repo into that path in your ComfyUI and the error should be gone.

I have re git it. it‘’s working. I didn't come Close it. Thank you. i'll close it
