### ISSUE TITLE
requirements error

### ISSUE THREAD

**Issue by clocad** [if-ai/ComfyUI-IF_MemoAvatar#3]
![gzzfxnNf8s](https://github.com/user-attachments/assets/5e124e2a-02f2-432b-9430-b5a1ab87f6a8)

**Comment by if-ai** [comment]
Try deleting line 9 from the requirements.txt

Then follow the instructions at
https://pypi.org/project/funasr/

**Comment by clocad** [comment]
installing requirements without funars

![aNB2XfgkPt](https://github.com/user-attachments/assets/6f7f8d55-03c0-418d-a629-3ebcb863622f)

![rKXYfIq7M1](https://github.com/user-attachments/assets/570482c1-d8e4-45f5-b2a2-0c0342d321f4)

**Comment by if-ai** [comment]
yes you are missing python development packages to compile the moviepy 
this is the stepby step
On Windows, the `python-devel` package is not explicitly available as it is on Linux. However, the equivalent development tools needed for building Python extensions are included when you install Python with specific options enabled. Here’s how you can set it up:

---

### **Steps to Install the Equivalent of `python-devel` on Windows**

#### 1. **Download and Install Python**
   - Download Python from the official [[Python website](https://www.python.org/downloads/)](https://www.python.org/downloads/).
   - Run the installer and ensure you:
     - Select **"Add Python to PATH"** during installation.
     - Choose **"Customize installation"**.
     - Ensure the **"Development headers"** option is checked. This installs the necessary header files like `Python.h`.

#### 2. **Install Microsoft C++ Build Tools**
   Many Python packages with C extensions require a C++ compiler. You need to install the Microsoft C++ Build Tools:
   - Download the **Build Tools for Visual Studio** from [[here](https://visualstudio.microsoft.com/visual-cpp-build-tools/)](https://visualstudio.microsoft.com/visual-cpp-build-tools/).
   - During installation, select the **"C++ Build Tools"** workload.
     - Also include the **"Windows 10 SDK"** and the **"C++ x64/x86 build tools"** components.

#### 3. **Verify Installation**
   After installation:
   - Open a Command Prompt or preferred terminal.
   - Check if Python is installed properly:
     ```cmd
     python --version
     ```
   - Verify that the build tools are accessible:
     ```cmd
     cl
     ```
     This should display the Microsoft C++ Compiler version information.

#### 4. **Test Installation**
   Try installing a package that requires C extensions. For example:
   ```cmd
   pip install moviepy==1.0.3
   ```
   If it compiles without errors, your environment is set up correctly.

I have a similar guide I made here  if you want to reference the MSVisualStudio
https://ko-fi.com/post/Installing-Triton-and-Sage-Attention-Flash-Attenti-P5P8175434

**Comment by dvoidus** [comment]
Same for me, fails to install funasr module:

```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2->funasr==1.1.17)
  Using cached aliyun-python-sdk-core-2.16.0.tar.gz (449 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "***\pip-install-_gfiyn6e\aliyun-python-sdk-core_0a7c814d1dda48019be2db776a24bebe\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dvoidus** [comment]
Ok, so this solution helped (downgrading aliyun-python-sdk-core):
```
pip install aliyun-python-sdk-core==2.13.10
pip install -U FunASR
```

**Comment by CapoFortuna** [comment]
> yes you are missing python development packages to compile the moviepy this is the stepby step On Windows, the `python-devel` package is not explicitly available as it is on Linux. However, the equivalent development tools needed for building Python extensions are included when you install Python with specific options enabled. Here’s how you can set it up:
> 
> ### **Steps to Install the Equivalent of `python-devel` on Windows**
> #### 1. **Download and Install Python**
> * Download Python from the official [[Python website](https://www.python.org/downloads/)](https://www.python.org/downloads/).
> * Run the installer and ensure you:
>   
>   * Select **"Add Python to PATH"** during installation.
>   * Choose **"Customize installation"**.
>   * Ensure the **"Development headers"** option is checked. This installs the necessary header files like `Python.h`.
> 
> #### 2. **Install Microsoft C++ Build Tools**
> Many Python packages with C extensions require a C++ compiler. You need to install the Microsoft C++ Build Tools:
> 
> * Download the **Build Tools for Visual Studio** from [[here](https://visualstudio.microsoft.com/visual-cpp-build-tools/)](https://visualstudio.microsoft.com/visual-cpp-build-tools/).
> * During installation, select the **"C++ Build Tools"** workload.
>   
>   * Also include the **"Windows 10 SDK"** and the **"C++ x64/x86 build tools"** components.
> 
> #### 3. **Verify Installation**
> After installation:
> 
> * Open a Command Prompt or preferred terminal.
> * Check if Python is installed properly:
>   ```batchfile
>   python --version
>   ```
> * Verify that the build tools are accessible:
>   ```batchfile
>   cl
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This should display the Microsoft C++ Compiler version information.
> 
> #### 4. **Test Installation**
> Try installing a package that requires C extensions. For example:
> 
> ```batchfile
> pip install moviepy==1.0.3
> ```
> 
> If it compiles without errors, your environment is set up correctly.
> 
> I have a similar guide I made here if you want to reference the MSVisualStudio https://ko-fi.com/post/Installing-Triton-and-Sage-Attention-Flash-Attenti-P5P8175434

![image](https://github.com/user-attachments/assets/c363f8be-c8df-431e-87e5-87738db94473)

Hello! I've done everythings here but keep getting this error

**Comment by if-ai** [comment]
did you try doing a 
cd to x:\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar
and do `git pull` 
for the lates code
