### ISSUE TITLE
python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__     assert 'detection' in self.models

### ISSUE THREAD

**Issue by zaitaxiang2012** [if-ai/ComfyUI-IF_MemoAvatar#4]
Loading models
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'attention_type': 'default', 'center_input_sample': False, 'class_embeddings_concat': False, 'conv_in_kernel': 3, 'dropout': 0.0, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'mid_block_only_cross_attention': None, 'num_attention_heads': None, 'projection_class_embeddings_input_dim': None, 'reverse_transformer_layers_per_block': None, 'time_cond_proj_dim': None, 'time_embedding_act_fn': None, 'time_embedding_dim': None, 'time_embedding_type': 'positional', 'timestep_post_act': None, 'transformer_layers_per_block': 1} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Models loaded successfully to cuda with dtype torch.float16
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.3-shuziren0912\custom_nodes\ComfyUI-IF_MemoAvatar-main\IF_MemoAvatar.py", line 131, in generate
    pixel_values, face_emb = preprocess_image(
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI-aki-v1.3-shuziren0912\custom_nodes\ComfyUI-IF_MemoAvatar-main\memo\utils\vision_utils.py", line 47, in preprocess_image
    face_analysis = FaceAnalysis(
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
==================
IF_AI_tool_output:
==================
❌ Error:

**Comment by nmandic78** [comment]
Same error on Ubuntu. I should probably search where it expects models to be as instructions in README.md are unclear. Or maybe @if-ai can help. Tnx!

**Comment by guahunyo** [comment]
Same error win10 cu124 torch2.5.1

**Comment by guahunyo** [comment]
I see. The models in D:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis are not taken out of the models folder, but copied. These files must also be in the models folder.

**Comment by if-ai** [comment]
> I see. The models in D:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis are not taken out of the models folder, but copied. These files must also be in the models folder.

did this solved I made some fixes to the repo to fix this models issues 

you need to move to the custom node folder and do a

cd x:\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar

`git pull`

to get all the recent updates

**Comment by nmandic78** [comment]
You have hardcoded 'model.pb' somewhere:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'

**Comment by nmandic78** [comment]
```
Saving Vocals stem to Melina_original-16k_(Vocals)_Kim_Vocal_2.wav...
Audio duration is 0.00 hours (10.44 seconds).
Using pydub for writing.
Clearing input audio file paths, sources and stems...
Separation duration: 00:00:08
Downloading emotion2vec models from modelscope
Traceback (most recent call last):
  File "/home/neman/ComfyUI/custom_nodes/ComfyUI-IF_MemoAvatar/IF_MemoAvatar.py", line 132, in generate
    audio_emotion, num_emotion_classes = extract_audio_emotion_labels(
  File "/home/neman/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/neman/ComfyUI/custom_nodes/ComfyUI-IF_MemoAvatar/memo/utils/audio_utils.py", line 178, in extract_audio_emotion_labels
    emotion_model = Emotion2vec(**kwargs, vocab_size=-1).to(device)
  File "/home/neman/miniconda3/lib/python3.10/site-packages/funasr/models/emotion2vec/model.py", line 45, in __init__
    cfg = OmegaConf.create(kwargs["model_conf"])
KeyError: 'model_conf'
Prompt executed in 14.59 seconds
```

**Comment by if-ai** [comment]
> You have hardcoded 'model.pb' somewhere: FileNotFoundError: [Errno 2] No such file or directory: '/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'

hmm I didn't hardcoded that but I made some changes to try and fix it can you please  git pull the repo and test it please

**Comment by guahunyo** [comment]
> You have hardcoded 'model.pb' somewhere:您已在某处硬编码“model.pb”： FileNotFoundError: [Errno 2] No such file or directory: '/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'FileNotFoundError：[Errno 2]没有这样的文件或目录：'/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'

This was because of missing configuration.json in models\emotion2vec\emotion2vec_plus_large folder I installed this file from huggingface which solved the problem

**Comment by nmandic78** [comment]
> > You have hardcoded 'model.pb' somewhere:您已在某处硬编码“model.pb”： FileNotFoundError: [Errno 2] No such file or directory: '/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'FileNotFoundError：[Errno 2]没有这样的文件或目录：'/home/ComfyUI/models/emotion2vec/emotion2vec_plus_large/model.pb'
> 
> This was because of missing configuration.json in models\emotion2vec\emotion2vec_plus_large folder I installed this file from huggingface which solved the problem

This solved it. Couldn't deduce from error message. Tnx!

**Comment by if-ai** [comment]
I also added a fix for the auto downloads  now
